declare module "@editorjs/image"
declare module "@editorjs/paragraph"
declare module "@editorjs/list"
declare module '@editorjs/checklist';
declare module "@editorjs/simple-image";
declare module '@editorjs/link';
declare module '@editorjs/raw';
declare module '@editorjs/embed';
declare module '@editorjs/quote';
declare module '@editorjs/table';
declare module '@alkhipce/editorjs-aitext';
declare module '@editorjs/warning';
declare module '@editorjs/delimiter';
declare module 'editorjs-paragraph-with-alignment@3.x';
declare module 'editorjs-alert';
declare module 'editorjs-paragraph-with-alignment';
declare module 'editorjs-text-color-plugin';
declare module '@sotaproject/strikethrough';
declare module '@editorjs/marker';
declare module 'editorjs-tooltip';
declare module 'editorjs-style';
declare module 'editorjs-html';
declare module 'editorjs-to-html';
